# fly.toml app configuration file generated for springtodoapp on 2024-02-04T15:18:45+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "springtodoapp"
primary_region = "arn"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
